// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlc

import (
	"context"
)

const createOwnership = `-- name: CreateOwnership :one
INSERT INTO ownerships (id, user_id, game_id, type, price, gifted_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, game_id) DO NOTHING
RETURNING id, user_id, game_id, type, price, gifted_by, created_at
`

type CreateOwnershipParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	GameID   string `json:"game_id"`
	Type     string `json:"type"`
	Price    int32  `json:"price"`
	GiftedBy string `json:"gifted_by"`
}

func (q *Queries) CreateOwnership(ctx context.Context, arg CreateOwnershipParams) (Ownership, error) {
	row := q.db.QueryRow(ctx, createOwnership,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.Type,
		arg.Price,
		arg.GiftedBy,
	)
	var i Ownership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Price,
		&i.GiftedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at
`

type CreatePaymentParams struct {
	ID                string `json:"id"`
	YkID              string `json:"yk_id"`
	UserID            string `json:"user_id"`
	GameID            string `json:"game_id"`
	Kind              string `json:"kind"`
	Amount            int32  `json:"amount"`
	CommissionPercent int32  `json:"commission_percent"`
	CommissionAmount  int32  `json:"commission_amount"`
	Status            string `json:"status"`
	FriendUsername    string `json:"friend_username"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.YkID,
		arg.UserID,
		arg.GameID,
		arg.Kind,
		arg.Amount,
		arg.CommissionPercent,
		arg.CommissionAmount,
		arg.Status,
		arg.FriendUsername,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, user_id, game_id, developer_id, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, game_id, developer_id, price, active, started_at
`

type CreateSubscriptionParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	GameID      string `json:"game_id"`
	DeveloperID string `json:"developer_id"`
	Price       int32  `json:"price"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.DeveloperID,
		arg.Price,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.DeveloperID,
		&i.Price,
		&i.Active,
		&i.StartedAt,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, game_id, developer_id, price, active, started_at FROM subscriptions WHERE user_id = $1 AND game_id = $2 AND active = TRUE
`

type GetActiveSubscriptionParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.UserID, arg.GameID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.DeveloperID,
		&i.Price,
		&i.Active,
		&i.StartedAt,
	)
	return i, err
}

const getOwnership = `-- name: GetOwnership :one
SELECT id, user_id, game_id, type, price, gifted_by, created_at FROM ownerships WHERE user_id = $1 AND game_id = $2
`

type GetOwnershipParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) GetOwnership(ctx context.Context, arg GetOwnershipParams) (Ownership, error) {
	row := q.db.QueryRow(ctx, getOwnership, arg.UserID, arg.GameID)
	var i Ownership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Price,
		&i.GiftedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByYkID = `-- name: GetPaymentByYkID :one
SELECT id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at FROM payments WHERE yk_id = $1
`

func (q *Queries) GetPaymentByYkID(ctx context.Context, ykID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByYkID, ykID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnershipsByUser = `-- name: ListOwnershipsByUser :many
SELECT id, user_id, game_id, type, price, gifted_by, created_at FROM ownerships WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOwnershipsByUser(ctx context.Context, userID string) ([]Ownership, error) {
	rows, err := q.db.Query(ctx, listOwnershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ownership
	for rows.Next() {
		var i Ownership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Price,
			&i.GiftedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT id, user_id, game_id, developer_id, price, active, started_at FROM subscriptions WHERE user_id = $1 AND active = TRUE ORDER BY started_at DESC
`

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.DeveloperID,
			&i.Price,
			&i.Active,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentYkID = `-- name: SetPaymentYkID :exec
UPDATE payments SET yk_id = $2 WHERE id = $1
`

type SetPaymentYkIDParams struct {
	ID   string `json:"id"`
	YkID string `json:"yk_id"`
}

func (q *Queries) SetPaymentYkID(ctx context.Context, arg SetPaymentYkIDParams) error {
	_, err := q.db.Exec(ctx, setPaymentYkID, arg.ID, arg.YkID)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $2 WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
