// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlc

import (
	"context"
	"time"
)

const createOwnership = `-- name: CreateOwnership :one
INSERT INTO ownerships (id, user_id, game_id, type, price, gifted_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, game_id) DO NOTHING
RETURNING id, user_id, game_id, type, price, gifted_by, created_at
`

type CreateOwnershipParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	GameID   string `json:"game_id"`
	Type     string `json:"type"`
	Price    int32  `json:"price"`
	GiftedBy string `json:"gifted_by"`
}

func (q *Queries) CreateOwnership(ctx context.Context, arg CreateOwnershipParams) (Ownership, error) {
	row := q.db.QueryRow(ctx, createOwnership,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.Type,
		arg.Price,
		arg.GiftedBy,
	)
	var i Ownership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Price,
		&i.GiftedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at, plan_id, sub_id, payment_method_id
`

type CreatePaymentParams struct {
	ID                string `json:"id"`
	YkID              string `json:"yk_id"`
	UserID            string `json:"user_id"`
	GameID            string `json:"game_id"`
	Kind              string `json:"kind"`
	Amount            int32  `json:"amount"`
	CommissionPercent int32  `json:"commission_percent"`
	CommissionAmount  int32  `json:"commission_amount"`
	Status            string `json:"status"`
	FriendUsername    string `json:"friend_username"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.YkID,
		arg.UserID,
		arg.GameID,
		arg.Kind,
		arg.Amount,
		arg.CommissionPercent,
		arg.CommissionAmount,
		arg.Status,
		arg.FriendUsername,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
		&i.PlanID,
		&i.SubID,
		&i.PaymentMethodID,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, user_id, game_id, developer_id, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id
`

type CreateSubscriptionParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	GameID      string `json:"game_id"`
	DeveloperID string `json:"developer_id"`
	Price       int32  `json:"price"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.DeveloperID,
		arg.Price,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.DeveloperID,
		&i.Price,
		&i.Active,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.PaymentMethodID,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :exec
UPDATE subscriptions SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateSubscription(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateSubscription, id)
	return err
}

const deleteOwnership = `-- name: DeleteOwnership :exec
DELETE FROM ownerships WHERE user_id = $1 AND game_id = $2
`

type DeleteOwnershipParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) DeleteOwnership(ctx context.Context, arg DeleteOwnershipParams) error {
	_, err := q.db.Exec(ctx, deleteOwnership, arg.UserID, arg.GameID)
	return err
}

const extendSubscription = `-- name: ExtendSubscription :exec
UPDATE subscriptions
SET expires_at = $2
WHERE id = $1
`

type ExtendSubscriptionParams struct {
	ID        string     `json:"id"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) error {
	_, err := q.db.Exec(ctx, extendSubscription, arg.ID, arg.ExpiresAt)
	return err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id FROM subscriptions WHERE user_id = $1 AND game_id = $2 AND active = TRUE
`

type GetActiveSubscriptionParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.UserID, arg.GameID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.DeveloperID,
		&i.Price,
		&i.Active,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.PaymentMethodID,
	)
	return i, err
}

const getGameIDBySlugOrID = `-- name: GetGameIDBySlugOrID :one
SELECT id FROM games WHERE id = $1 OR slug = $1
`

func (q *Queries) GetGameIDBySlugOrID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getGameIDBySlugOrID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getOwnership = `-- name: GetOwnership :one
SELECT id, user_id, game_id, type, price, gifted_by, created_at FROM ownerships WHERE user_id = $1 AND game_id = $2
`

type GetOwnershipParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) GetOwnership(ctx context.Context, arg GetOwnershipParams) (Ownership, error) {
	row := q.db.QueryRow(ctx, getOwnership, arg.UserID, arg.GameID)
	var i Ownership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Price,
		&i.GiftedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at, plan_id, sub_id, payment_method_id FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
		&i.PlanID,
		&i.SubID,
		&i.PaymentMethodID,
	)
	return i, err
}

const getPaymentByYkID = `-- name: GetPaymentByYkID :one
SELECT id, yk_id, user_id, game_id, kind, amount, commission_percent, commission_amount, status, friend_username, created_at, plan_id, sub_id, payment_method_id FROM payments WHERE yk_id = $1
`

func (q *Queries) GetPaymentByYkID(ctx context.Context, ykID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByYkID, ykID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.YkID,
		&i.UserID,
		&i.GameID,
		&i.Kind,
		&i.Amount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.FriendUsername,
		&i.CreatedAt,
		&i.PlanID,
		&i.SubID,
		&i.PaymentMethodID,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.DeveloperID,
		&i.Price,
		&i.Active,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.PaymentMethodID,
	)
	return i, err
}

const getUserSubscriptionStatus = `-- name: GetUserSubscriptionStatus :one
SELECT s.active, s.expires_at
FROM subscriptions s
JOIN games g ON g.id = s.game_id
WHERE s.user_id = $1
  AND (g.id = $2 OR g.slug = $2)
  AND s.active = TRUE
LIMIT 1
`

type GetUserSubscriptionStatusParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetUserSubscriptionStatusRow struct {
	Active    bool       `json:"active"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) GetUserSubscriptionStatus(ctx context.Context, arg GetUserSubscriptionStatusParams) (GetUserSubscriptionStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionStatus, arg.UserID, arg.ID)
	var i GetUserSubscriptionStatusRow
	err := row.Scan(&i.Active, &i.ExpiresAt)
	return i, err
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id FROM subscriptions
WHERE active = TRUE
  AND expires_at IS NOT NULL
  AND payment_method_id != ''
  AND expires_at <= $1
ORDER BY expires_at
`

func (q *Queries) ListExpiringSubscriptions(ctx context.Context, expiresAt *time.Time) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.DeveloperID,
			&i.Price,
			&i.Active,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.PaymentMethodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnershipsByUser = `-- name: ListOwnershipsByUser :many
SELECT id, user_id, game_id, type, price, gifted_by, created_at FROM ownerships WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOwnershipsByUser(ctx context.Context, userID string) ([]Ownership, error) {
	rows, err := q.db.Query(ctx, listOwnershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ownership
	for rows.Next() {
		var i Ownership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Price,
			&i.GiftedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id FROM subscriptions WHERE user_id = $1 AND active = TRUE ORDER BY started_at DESC
`

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.DeveloperID,
			&i.Price,
			&i.Active,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.PaymentMethodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsWithExpiry = `-- name: ListSubscriptionsWithExpiry :many
SELECT id, user_id, game_id, developer_id, price, active, started_at, expires_at, payment_method_id FROM subscriptions WHERE user_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListSubscriptionsWithExpiry(ctx context.Context, userID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsWithExpiry, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.DeveloperID,
			&i.Price,
			&i.Active,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.PaymentMethodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentMethodID = `-- name: SetPaymentMethodID :exec
UPDATE payments SET payment_method_id = $2 WHERE id = $1
`

type SetPaymentMethodIDParams struct {
	ID              string `json:"id"`
	PaymentMethodID string `json:"payment_method_id"`
}

func (q *Queries) SetPaymentMethodID(ctx context.Context, arg SetPaymentMethodIDParams) error {
	_, err := q.db.Exec(ctx, setPaymentMethodID, arg.ID, arg.PaymentMethodID)
	return err
}

const setPaymentSubID = `-- name: SetPaymentSubID :exec
UPDATE payments SET sub_id = $2 WHERE id = $1
`

type SetPaymentSubIDParams struct {
	ID    string  `json:"id"`
	SubID *string `json:"sub_id"`
}

func (q *Queries) SetPaymentSubID(ctx context.Context, arg SetPaymentSubIDParams) error {
	_, err := q.db.Exec(ctx, setPaymentSubID, arg.ID, arg.SubID)
	return err
}

const setPaymentYkID = `-- name: SetPaymentYkID :exec
UPDATE payments SET yk_id = $2 WHERE id = $1
`

type SetPaymentYkIDParams struct {
	ID   string `json:"id"`
	YkID string `json:"yk_id"`
}

func (q *Queries) SetPaymentYkID(ctx context.Context, arg SetPaymentYkIDParams) error {
	_, err := q.db.Exec(ctx, setPaymentYkID, arg.ID, arg.YkID)
	return err
}

const setSubscriptionRenewalInfo = `-- name: SetSubscriptionRenewalInfo :exec
UPDATE subscriptions
SET expires_at = $2, payment_method_id = $3
WHERE id = $1
`

type SetSubscriptionRenewalInfoParams struct {
	ID              string     `json:"id"`
	ExpiresAt       *time.Time `json:"expires_at"`
	PaymentMethodID string     `json:"payment_method_id"`
}

func (q *Queries) SetSubscriptionRenewalInfo(ctx context.Context, arg SetSubscriptionRenewalInfoParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionRenewalInfo, arg.ID, arg.ExpiresAt, arg.PaymentMethodID)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $2 WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
