// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devapi.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO developer_api_keys (id, developer_id, name, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, developer_id, name, key_hash, created_at, last_used_at, revoked
`

type CreateAPIKeyParams struct {
	ID          string `json:"id"`
	DeveloperID string `json:"developer_id"`
	Name        string `json:"name"`
	KeyHash     string `json:"key_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (DeveloperApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.DeveloperID,
		arg.Name,
		arg.KeyHash,
	)
	var i DeveloperApiKey
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const createLaunchToken = `-- name: CreateLaunchToken :exec
INSERT INTO launch_tokens (token_hash, user_id, game_id)
VALUES ($1, $2, $3)
`

type CreateLaunchTokenParams struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	GameID    string `json:"game_id"`
}

func (q *Queries) CreateLaunchToken(ctx context.Context, arg CreateLaunchTokenParams) error {
	_, err := q.db.Exec(ctx, createLaunchToken, arg.TokenHash, arg.UserID, arg.GameID)
	return err
}

const deleteLaunchToken = `-- name: DeleteLaunchToken :exec
DELETE FROM launch_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteLaunchToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteLaunchToken, tokenHash)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, developer_id, name, key_hash, created_at, last_used_at, revoked FROM developer_api_keys
WHERE key_hash = $1 AND revoked = FALSE
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (DeveloperApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i DeveloperApiKey
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const getGameDeveloperID = `-- name: GetGameDeveloperID :one
SELECT developer_id FROM games WHERE id = $1 OR slug = $1
`

func (q *Queries) GetGameDeveloperID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getGameDeveloperID, id)
	var developer_id string
	err := row.Scan(&developer_id)
	return developer_id, err
}

const getLaunchToken = `-- name: GetLaunchToken :one
SELECT lt.user_id, lt.game_id, lt.expires_at,
       COALESCE(s.active, FALSE) AS subscribed,
       s.expires_at              AS sub_expires_at
FROM launch_tokens lt
LEFT JOIN subscriptions s
    ON s.user_id = lt.user_id AND s.game_id = lt.game_id AND s.active = TRUE
WHERE lt.token_hash = $1 AND lt.expires_at > now()
LIMIT 1
`

type GetLaunchTokenRow struct {
	UserID       string             `json:"user_id"`
	GameID       string             `json:"game_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Subscribed   bool               `json:"subscribed"`
	SubExpiresAt *time.Time         `json:"sub_expires_at"`
}

func (q *Queries) GetLaunchToken(ctx context.Context, tokenHash string) (GetLaunchTokenRow, error) {
	row := q.db.QueryRow(ctx, getLaunchToken, tokenHash)
	var i GetLaunchTokenRow
	err := row.Scan(
		&i.UserID,
		&i.GameID,
		&i.ExpiresAt,
		&i.Subscribed,
		&i.SubExpiresAt,
	)
	return i, err
}

const getSubscriptionForVerify = `-- name: GetSubscriptionForVerify :one
SELECT s.active, s.expires_at
FROM subscriptions s
JOIN games g ON g.id = s.game_id
WHERE s.user_id = $1
  AND s.game_id = $2
  AND g.developer_id = $3
  AND s.active = TRUE
LIMIT 1
`

type GetSubscriptionForVerifyParams struct {
	UserID      string `json:"user_id"`
	GameID      string `json:"game_id"`
	DeveloperID string `json:"developer_id"`
}

type GetSubscriptionForVerifyRow struct {
	Active    bool       `json:"active"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) GetSubscriptionForVerify(ctx context.Context, arg GetSubscriptionForVerifyParams) (GetSubscriptionForVerifyRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForVerify, arg.UserID, arg.GameID, arg.DeveloperID)
	var i GetSubscriptionForVerifyRow
	err := row.Scan(&i.Active, &i.ExpiresAt)
	return i, err
}

const listAPIKeysByDeveloper = `-- name: ListAPIKeysByDeveloper :many
SELECT id, developer_id, name, created_at, last_used_at, revoked
FROM developer_api_keys
WHERE developer_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByDeveloperRow struct {
	ID          string             `json:"id"`
	DeveloperID string             `json:"developer_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  *time.Time         `json:"last_used_at"`
	Revoked     bool               `json:"revoked"`
}

func (q *Queries) ListAPIKeysByDeveloper(ctx context.Context, developerID string) ([]ListAPIKeysByDeveloperRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByDeveloper, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByDeveloperRow
	for rows.Next() {
		var i ListAPIKeysByDeveloperRow
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeLaunchTokens = `-- name: PurgeLaunchTokens :exec
DELETE FROM launch_tokens WHERE expires_at < now()
`

func (q *Queries) PurgeLaunchTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeLaunchTokens)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE developer_api_keys
SET revoked = TRUE
WHERE id = $1 AND developer_id = $2
`

type RevokeAPIKeyParams struct {
	ID          string `json:"id"`
	DeveloperID string `json:"developer_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.DeveloperID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE developer_api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
