// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package sqlc

import (
	"context"
	"time"
)

const countOwnersByGame = `-- name: CountOwnersByGame :one
SELECT count(*)::int FROM ownerships WHERE game_id = $1
`

func (q *Queries) CountOwnersByGame(ctx context.Context, gameID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnersByGame, gameID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSubscribersByGame = `-- name: CountSubscribersByGame :one
SELECT count(*)::int FROM subscriptions WHERE game_id = $1 AND active
`

func (q *Queries) CountSubscribersByGame(ctx context.Context, gameID string) (int32, error) {
	row := q.db.QueryRow(ctx, countSubscribersByGame, gameID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    id, slug, title, tagline, description, genre, tags,
    developer_id, developer_name, cover_image, screenshots,
    has_browser_build, browser_build_url,
    has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms,
    supports_multiplayer, pricing_model, price, friend_pack_discount,
    sub_enabled, sub_price, sub_benefits, sub_chat_link,
    demo_enabled, demo_starts_at, demo_ends_at,
    theme, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25, $26,
    $27, $28, $29,
    $30, $31
)
RETURNING id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at
`

type CreateGameParams struct {
	ID                  string     `json:"id"`
	Slug                string     `json:"slug"`
	Title               string     `json:"title"`
	Tagline             string     `json:"tagline"`
	Description         string     `json:"description"`
	Genre               string     `json:"genre"`
	Tags                []string   `json:"tags"`
	DeveloperID         string     `json:"developer_id"`
	DeveloperName       string     `json:"developer_name"`
	CoverImage          string     `json:"cover_image"`
	Screenshots         []string   `json:"screenshots"`
	HasBrowserBuild     bool       `json:"has_browser_build"`
	BrowserBuildUrl     string     `json:"browser_build_url"`
	HasDownloadBuild    bool       `json:"has_download_build"`
	DownloadObjectKey   string     `json:"download_object_key"`
	DownloadFileName    string     `json:"download_file_name"`
	DownloadSizeMb      int32      `json:"download_size_mb"`
	DownloadPlatforms   []string   `json:"download_platforms"`
	SupportsMultiplayer bool       `json:"supports_multiplayer"`
	PricingModel        string     `json:"pricing_model"`
	Price               int32      `json:"price"`
	FriendPackDiscount  int32      `json:"friend_pack_discount"`
	SubEnabled          bool       `json:"sub_enabled"`
	SubPrice            int32      `json:"sub_price"`
	SubBenefits         []string   `json:"sub_benefits"`
	SubChatLink         string     `json:"sub_chat_link"`
	DemoEnabled         bool       `json:"demo_enabled"`
	DemoStartsAt        *time.Time `json:"demo_starts_at"`
	DemoEndsAt          *time.Time `json:"demo_ends_at"`
	Theme               []byte     `json:"theme"`
	Status              string     `json:"status"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Tagline,
		arg.Description,
		arg.Genre,
		arg.Tags,
		arg.DeveloperID,
		arg.DeveloperName,
		arg.CoverImage,
		arg.Screenshots,
		arg.HasBrowserBuild,
		arg.BrowserBuildUrl,
		arg.HasDownloadBuild,
		arg.DownloadObjectKey,
		arg.DownloadFileName,
		arg.DownloadSizeMb,
		arg.DownloadPlatforms,
		arg.SupportsMultiplayer,
		arg.PricingModel,
		arg.Price,
		arg.FriendPackDiscount,
		arg.SubEnabled,
		arg.SubPrice,
		arg.SubBenefits,
		arg.SubChatLink,
		arg.DemoEnabled,
		arg.DemoStartsAt,
		arg.DemoEndsAt,
		arg.Theme,
		arg.Status,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Description,
		&i.Genre,
		&i.Tags,
		&i.DeveloperID,
		&i.DeveloperName,
		&i.CoverImage,
		&i.Screenshots,
		&i.HasBrowserBuild,
		&i.BrowserBuildUrl,
		&i.HasDownloadBuild,
		&i.DownloadObjectKey,
		&i.DownloadFileName,
		&i.DownloadSizeMb,
		&i.DownloadPlatforms,
		&i.SupportsMultiplayer,
		&i.PricingModel,
		&i.Price,
		&i.FriendPackDiscount,
		&i.SubEnabled,
		&i.SubPrice,
		&i.SubBenefits,
		&i.SubChatLink,
		&i.DemoEnabled,
		&i.DemoStartsAt,
		&i.DemoEndsAt,
		&i.Theme,
		&i.Status,
		&i.Plays,
		&i.TrendingScore,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Description,
		&i.Genre,
		&i.Tags,
		&i.DeveloperID,
		&i.DeveloperName,
		&i.CoverImage,
		&i.Screenshots,
		&i.HasBrowserBuild,
		&i.BrowserBuildUrl,
		&i.HasDownloadBuild,
		&i.DownloadObjectKey,
		&i.DownloadFileName,
		&i.DownloadSizeMb,
		&i.DownloadPlatforms,
		&i.SupportsMultiplayer,
		&i.PricingModel,
		&i.Price,
		&i.FriendPackDiscount,
		&i.SubEnabled,
		&i.SubPrice,
		&i.SubBenefits,
		&i.SubChatLink,
		&i.DemoEnabled,
		&i.DemoStartsAt,
		&i.DemoEndsAt,
		&i.Theme,
		&i.Status,
		&i.Plays,
		&i.TrendingScore,
		&i.CreatedAt,
	)
	return i, err
}

const getGameBySlug = `-- name: GetGameBySlug :one
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games WHERE slug = $1
`

func (q *Queries) GetGameBySlug(ctx context.Context, slug string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameBySlug, slug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Description,
		&i.Genre,
		&i.Tags,
		&i.DeveloperID,
		&i.DeveloperName,
		&i.CoverImage,
		&i.Screenshots,
		&i.HasBrowserBuild,
		&i.BrowserBuildUrl,
		&i.HasDownloadBuild,
		&i.DownloadObjectKey,
		&i.DownloadFileName,
		&i.DownloadSizeMb,
		&i.DownloadPlatforms,
		&i.SupportsMultiplayer,
		&i.PricingModel,
		&i.Price,
		&i.FriendPackDiscount,
		&i.SubEnabled,
		&i.SubPrice,
		&i.SubBenefits,
		&i.SubChatLink,
		&i.DemoEnabled,
		&i.DemoStartsAt,
		&i.DemoEndsAt,
		&i.Theme,
		&i.Status,
		&i.Plays,
		&i.TrendingScore,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPlays = `-- name: IncrementPlays :exec
UPDATE games SET plays = plays + 1 WHERE id = $1
`

func (q *Queries) IncrementPlays(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementPlays, id)
	return err
}

const insertGameEvent = `-- name: InsertGameEvent :exec
INSERT INTO game_events (id, game_id, type) VALUES ($1, $2, $3)
`

type InsertGameEventParams struct {
	ID     string `json:"id"`
	GameID string `json:"game_id"`
	Type   string `json:"type"`
}

func (q *Queries) InsertGameEvent(ctx context.Context, arg InsertGameEventParams) error {
	_, err := q.db.Exec(ctx, insertGameEvent, arg.ID, arg.GameID, arg.Type)
	return err
}

const listGamesByDeveloper = `-- name: ListGamesByDeveloper :many
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games WHERE developer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGamesByDeveloper(ctx context.Context, developerID string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByDeveloper, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewest = `-- name: ListNewest :many
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games WHERE status = 'published' ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListNewest(ctx context.Context, limit int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, listNewest, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopular = `-- name: ListPopular :many
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games
WHERE status = 'published'
ORDER BY
    (SELECT count(*) FROM ownerships o WHERE o.game_id = games.id)
    + (SELECT count(*) FROM subscriptions s WHERE s.game_id = games.id AND s.active) DESC,
    created_at DESC
LIMIT $1
`

func (q *Queries) ListPopular(ctx context.Context, limit int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, listPopular, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedGames = `-- name: ListPublishedGames :many
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games WHERE status = 'published' ORDER BY created_at DESC
`

func (q *Queries) ListPublishedGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listPublishedGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrending = `-- name: ListTrending :many
SELECT id, slug, title, tagline, description, genre, tags, developer_id, developer_name, cover_image, screenshots, has_browser_build, browser_build_url, has_download_build, download_object_key, download_file_name, download_size_mb, download_platforms, supports_multiplayer, pricing_model, price, friend_pack_discount, sub_enabled, sub_price, sub_benefits, sub_chat_link, demo_enabled, demo_starts_at, demo_ends_at, theme, status, plays, trending_score, created_at FROM games
WHERE status = 'published' AND trending_score > 0
ORDER BY trending_score DESC
LIMIT $1
`

func (q *Queries) ListTrending(ctx context.Context, limit int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, listTrending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCounts = `-- name: OwnerCounts :many
SELECT game_id, count(*)::int AS n FROM ownerships GROUP BY game_id
`

type OwnerCountsRow struct {
	GameID string `json:"game_id"`
	N      int32  `json:"n"`
}

func (q *Queries) OwnerCounts(ctx context.Context) ([]OwnerCountsRow, error) {
	rows, err := q.db.Query(ctx, ownerCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountsRow
	for rows.Next() {
		var i OwnerCountsRow
		if err := rows.Scan(&i.GameID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeTrendingScores = `-- name: RecomputeTrendingScores :exec
UPDATE games g SET trending_score = COALESCE((
    SELECT sum(
        (CASE e.type WHEN 'acquire' THEN 5.0 WHEN 'play' THEN 2.0 ELSE 1.0 END)
        * exp(- extract(epoch FROM (now() - e.created_at)) / 604800.0)
    )
    FROM game_events e
    WHERE e.game_id = g.id AND e.created_at > now() - interval '7 days'
), 0)
`

func (q *Queries) RecomputeTrendingScores(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recomputeTrendingScores)
	return err
}

const setGameStatus = `-- name: SetGameStatus :exec
UPDATE games SET status = $2 WHERE id = $1
`

type SetGameStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetGameStatus(ctx context.Context, arg SetGameStatusParams) error {
	_, err := q.db.Exec(ctx, setGameStatus, arg.ID, arg.Status)
	return err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM games WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const subscriberCounts = `-- name: SubscriberCounts :many
SELECT game_id, count(*)::int AS n FROM subscriptions WHERE active GROUP BY game_id
`

type SubscriberCountsRow struct {
	GameID string `json:"game_id"`
	N      int32  `json:"n"`
}

func (q *Queries) SubscriberCounts(ctx context.Context) ([]SubscriberCountsRow, error) {
	rows, err := q.db.Query(ctx, subscriberCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriberCountsRow
	for rows.Next() {
		var i SubscriberCountsRow
		if err := rows.Scan(&i.GameID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
