// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlc

import (
	"context"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, reporter_id, target_type, target_id, reason, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, reporter_id, target_type, target_id, reason, details, status, resolution, handled_by, created_at, resolved_at
`

type CreateReportParams struct {
	ID         string `json:"id"`
	ReporterID string `json:"reporter_id"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Reason     string `json:"reason"`
	Details    string `json:"details"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.Resolution,
		&i.HandledBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, reporter_id, target_type, target_id, reason, details, status, resolution, handled_by, created_at, resolved_at FROM reports WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.Resolution,
		&i.HandledBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listAllReports = `-- name: ListAllReports :many
SELECT id, reporter_id, target_type, target_id, reason, details, status, resolution, handled_by, created_at, resolved_at FROM reports ORDER BY created_at DESC
`

func (q *Queries) ListAllReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.Query(ctx, listAllReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.Resolution,
			&i.HandledBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_id, target_type, target_id, reason, details, status, resolution, handled_by, created_at, resolved_at FROM reports WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReports(ctx context.Context, status string) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.Resolution,
			&i.HandledBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :exec
UPDATE reports
SET status = $2, resolution = $3, handled_by = $4, resolved_at = now()
WHERE id = $1
`

type ResolveReportParams struct {
	ID         string  `json:"id"`
	Status     string  `json:"status"`
	Resolution string  `json:"resolution"`
	HandledBy  *string `json:"handled_by"`
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) error {
	_, err := q.db.Exec(ctx, resolveReport,
		arg.ID,
		arg.Status,
		arg.Resolution,
		arg.HandledBy,
	)
	return err
}
