// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeveloperApiKey struct {
	ID          string             `json:"id"`
	DeveloperID string             `json:"developer_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  *time.Time         `json:"last_used_at"`
	Revoked     bool               `json:"revoked"`
}

type Game struct {
	ID                  string             `json:"id"`
	Slug                string             `json:"slug"`
	Title               string             `json:"title"`
	Tagline             string             `json:"tagline"`
	Description         string             `json:"description"`
	Genre               string             `json:"genre"`
	Tags                []string           `json:"tags"`
	DeveloperID         string             `json:"developer_id"`
	DeveloperName       string             `json:"developer_name"`
	CoverImage          string             `json:"cover_image"`
	Screenshots         []string           `json:"screenshots"`
	HasBrowserBuild     bool               `json:"has_browser_build"`
	BrowserBuildUrl     string             `json:"browser_build_url"`
	HasDownloadBuild    bool               `json:"has_download_build"`
	DownloadObjectKey   string             `json:"download_object_key"`
	DownloadFileName    string             `json:"download_file_name"`
	DownloadSizeMb      int32              `json:"download_size_mb"`
	DownloadPlatforms   []string           `json:"download_platforms"`
	SupportsMultiplayer bool               `json:"supports_multiplayer"`
	PricingModel        string             `json:"pricing_model"`
	Price               int32              `json:"price"`
	FriendPackDiscount  int32              `json:"friend_pack_discount"`
	SubEnabled          bool               `json:"sub_enabled"`
	SubPrice            int32              `json:"sub_price"`
	SubBenefits         []string           `json:"sub_benefits"`
	SubChatLink         string             `json:"sub_chat_link"`
	DemoEnabled         bool               `json:"demo_enabled"`
	DemoStartsAt        *time.Time         `json:"demo_starts_at"`
	DemoEndsAt          *time.Time         `json:"demo_ends_at"`
	Theme               []byte             `json:"theme"`
	Status              string             `json:"status"`
	Plays               int32              `json:"plays"`
	TrendingScore       float64            `json:"trending_score"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type GameEvent struct {
	ID        string             `json:"id"`
	GameID    string             `json:"game_id"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LaunchToken struct {
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	GameID    string             `json:"game_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Ownership struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	GameID    string             `json:"game_id"`
	Type      string             `json:"type"`
	Price     int32              `json:"price"`
	GiftedBy  string             `json:"gifted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                string             `json:"id"`
	YkID              string             `json:"yk_id"`
	UserID            string             `json:"user_id"`
	GameID            string             `json:"game_id"`
	Kind              string             `json:"kind"`
	Amount            int32              `json:"amount"`
	CommissionPercent int32              `json:"commission_percent"`
	CommissionAmount  int32              `json:"commission_amount"`
	Status            string             `json:"status"`
	FriendUsername    string             `json:"friend_username"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PlanID            *string            `json:"plan_id"`
	SubID             *string            `json:"sub_id"`
	PaymentMethodID   string             `json:"payment_method_id"`
}

type Payout struct {
	ID          string             `json:"id"`
	DeveloperID string             `json:"developer_id"`
	Amount      int32              `json:"amount"`
	Status      string             `json:"status"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Report struct {
	ID         string             `json:"id"`
	ReporterID string             `json:"reporter_id"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Reason     string             `json:"reason"`
	Details    string             `json:"details"`
	Status     string             `json:"status"`
	Resolution string             `json:"resolution"`
	HandledBy  *string            `json:"handled_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt *time.Time         `json:"resolved_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID                bool               `json:"id"`
	CommissionPercent int32              `json:"commission_percent"`
	TrendingEnabled   bool               `json:"trending_enabled"`
	PopularEnabled    bool               `json:"popular_enabled"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	GameID          string             `json:"game_id"`
	DeveloperID     string             `json:"developer_id"`
	Price           int32              `json:"price"`
	Active          bool               `json:"active"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	ExpiresAt       *time.Time         `json:"expires_at"`
	PaymentMethodID string             `json:"payment_method_id"`
}

type SubscriptionPlan struct {
	ID          string             `json:"id"`
	DeveloperID string             `json:"developer_id"`
	Name        string             `json:"name"`
	Price       int32              `json:"price"`
	Period      string             `json:"period"`
	Benefits    []string           `json:"benefits"`
	ChatLink    string             `json:"chat_link"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionPlanGame struct {
	PlanID string `json:"plan_id"`
	GameID string `json:"game_id"`
}

type User struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsDeveloper  bool               `json:"is_developer"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
