// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (id, developer_id, amount)
VALUES ($1, $2, $3)
RETURNING id, developer_id, amount, status, note, created_at, updated_at
`

type CreatePayoutParams struct {
	ID          string `json:"id"`
	DeveloperID string `json:"developer_id"`
	Amount      int32  `json:"amount"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout, arg.ID, arg.DeveloperID, arg.Amount)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeveloperEarnings = `-- name: GetDeveloperEarnings :one
SELECT COALESCE(SUM(p.amount - p.commission_amount), 0)::BIGINT AS total_earned
FROM payments p
JOIN games g ON g.id = p.game_id
WHERE g.developer_id = $1
  AND p.status = 'succeeded'
`

// Developer earnings: sum of (amount - commission) for all succeeded payments on their games.
func (q *Queries) GetDeveloperEarnings(ctx context.Context, developerID string) (int64, error) {
	row := q.db.QueryRow(ctx, getDeveloperEarnings, developerID)
	var total_earned int64
	err := row.Scan(&total_earned)
	return total_earned, err
}

const getDeveloperPayoutsTotal = `-- name: GetDeveloperPayoutsTotal :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total_requested
FROM payouts
WHERE developer_id = $1
  AND status != 'rejected'
`

// Total already requested (pending + paid); rejected ones don't count.
func (q *Queries) GetDeveloperPayoutsTotal(ctx context.Context, developerID string) (int64, error) {
	row := q.db.QueryRow(ctx, getDeveloperPayoutsTotal, developerID)
	var total_requested int64
	err := row.Scan(&total_requested)
	return total_requested, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, developer_id, amount, status, note, created_at, updated_at FROM payouts WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id string) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPayouts = `-- name: ListAllPayouts :many
SELECT po.id, po.developer_id, po.amount, po.status, po.note, po.created_at, po.updated_at, u.username AS developer_username
FROM payouts po
JOIN users u ON u.id = po.developer_id
ORDER BY po.created_at DESC
`

type ListAllPayoutsRow struct {
	ID                string             `json:"id"`
	DeveloperID       string             `json:"developer_id"`
	Amount            int32              `json:"amount"`
	Status            string             `json:"status"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeveloperUsername string             `json:"developer_username"`
}

func (q *Queries) ListAllPayouts(ctx context.Context) ([]ListAllPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listAllPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPayoutsRow
	for rows.Next() {
		var i ListAllPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeveloperUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByDeveloper = `-- name: ListPayoutsByDeveloper :many
SELECT id, developer_id, amount, status, note, created_at, updated_at FROM payouts WHERE developer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPayoutsByDeveloper(ctx context.Context, developerID string) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByDeveloper, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE payouts
SET status = $2, note = $3, updated_at = now()
WHERE id = $1
RETURNING id, developer_id, amount, status, note, created_at, updated_at
`

type UpdatePayoutStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
	Note   string `json:"note"`
}

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus, arg.ID, arg.Status, arg.Note)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
