// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, commission_percent, trending_enabled, popular_enabled, updated_at FROM settings WHERE id = TRUE
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.CommissionPercent,
		&i.TrendingEnabled,
		&i.PopularEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET commission_percent = $1,
    trending_enabled = $2,
    popular_enabled = $3,
    updated_at = now()
WHERE id = TRUE
RETURNING id, commission_percent, trending_enabled, popular_enabled, updated_at
`

type UpdateSettingsParams struct {
	CommissionPercent int32 `json:"commission_percent"`
	TrendingEnabled   bool  `json:"trending_enabled"`
	PopularEnabled    bool  `json:"popular_enabled"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.CommissionPercent, arg.TrendingEnabled, arg.PopularEnabled)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.CommissionPercent,
		&i.TrendingEnabled,
		&i.PopularEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
