// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_plans.sql

package sqlc

import (
	"context"
)

const addGameToPlan = `-- name: AddGameToPlan :exec
INSERT INTO subscription_plan_games (plan_id, game_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGameToPlanParams struct {
	PlanID string `json:"plan_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) AddGameToPlan(ctx context.Context, arg AddGameToPlanParams) error {
	_, err := q.db.Exec(ctx, addGameToPlan, arg.PlanID, arg.GameID)
	return err
}

const getPlanByDeveloper = `-- name: GetPlanByDeveloper :one
SELECT id, developer_id, name, price, period, benefits, chat_link, active, created_at FROM subscription_plans WHERE developer_id = $1
`

func (q *Queries) GetPlanByDeveloper(ctx context.Context, developerID string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByDeveloper, developerID)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Price,
		&i.Period,
		&i.Benefits,
		&i.ChatLink,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, developer_id, name, price, period, benefits, chat_link, active, created_at FROM subscription_plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Price,
		&i.Period,
		&i.Benefits,
		&i.ChatLink,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanForGameKey = `-- name: GetPlanForGameKey :one
SELECT sp.id, sp.developer_id, sp.name, sp.price, sp.period, sp.benefits, sp.chat_link, sp.active, sp.created_at FROM subscription_plans sp
JOIN games g ON g.developer_id = sp.developer_id
WHERE (g.id = $1 OR g.slug = $1) AND sp.active = TRUE
LIMIT 1
`

func (q *Queries) GetPlanForGameKey(ctx context.Context, id string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanForGameKey, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Price,
		&i.Period,
		&i.Benefits,
		&i.ChatLink,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanGameIDs = `-- name: ListPlanGameIDs :many
SELECT game_id FROM subscription_plan_games WHERE plan_id = $1
`

func (q *Queries) ListPlanGameIDs(ctx context.Context, planID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlanGameIDs, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var game_id string
		if err := rows.Scan(&game_id); err != nil {
			return nil, err
		}
		items = append(items, game_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanGames = `-- name: ListPlanGames :many
SELECT g.id, g.slug, g.title, g.tagline, g.description, g.genre, g.tags, g.developer_id, g.developer_name, g.cover_image, g.screenshots, g.has_browser_build, g.browser_build_url, g.has_download_build, g.download_object_key, g.download_file_name, g.download_size_mb, g.download_platforms, g.supports_multiplayer, g.pricing_model, g.price, g.friend_pack_discount, g.sub_enabled, g.sub_price, g.sub_benefits, g.sub_chat_link, g.demo_enabled, g.demo_starts_at, g.demo_ends_at, g.theme, g.status, g.plays, g.trending_score, g.created_at FROM games g
JOIN subscription_plan_games spg ON spg.game_id = g.id
WHERE spg.plan_id = $1
ORDER BY g.created_at DESC
`

func (q *Queries) ListPlanGames(ctx context.Context, planID string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listPlanGames, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Description,
			&i.Genre,
			&i.Tags,
			&i.DeveloperID,
			&i.DeveloperName,
			&i.CoverImage,
			&i.Screenshots,
			&i.HasBrowserBuild,
			&i.BrowserBuildUrl,
			&i.HasDownloadBuild,
			&i.DownloadObjectKey,
			&i.DownloadFileName,
			&i.DownloadSizeMb,
			&i.DownloadPlatforms,
			&i.SupportsMultiplayer,
			&i.PricingModel,
			&i.Price,
			&i.FriendPackDiscount,
			&i.SubEnabled,
			&i.SubPrice,
			&i.SubBenefits,
			&i.SubChatLink,
			&i.DemoEnabled,
			&i.DemoStartsAt,
			&i.DemoEndsAt,
			&i.Theme,
			&i.Status,
			&i.Plays,
			&i.TrendingScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGameFromPlan = `-- name: RemoveGameFromPlan :exec
DELETE FROM subscription_plan_games WHERE plan_id = $1 AND game_id = $2
`

type RemoveGameFromPlanParams struct {
	PlanID string `json:"plan_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) RemoveGameFromPlan(ctx context.Context, arg RemoveGameFromPlanParams) error {
	_, err := q.db.Exec(ctx, removeGameFromPlan, arg.PlanID, arg.GameID)
	return err
}

const setPaymentPlanID = `-- name: SetPaymentPlanID :exec
UPDATE payments SET plan_id = $2 WHERE id = $1
`

type SetPaymentPlanIDParams struct {
	ID     string  `json:"id"`
	PlanID *string `json:"plan_id"`
}

func (q *Queries) SetPaymentPlanID(ctx context.Context, arg SetPaymentPlanIDParams) error {
	_, err := q.db.Exec(ctx, setPaymentPlanID, arg.ID, arg.PlanID)
	return err
}

const upsertSubscriptionPlan = `-- name: UpsertSubscriptionPlan :one
INSERT INTO subscription_plans (id, developer_id, name, price, period, benefits, chat_link)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (developer_id) DO UPDATE SET
    name      = EXCLUDED.name,
    price     = EXCLUDED.price,
    period    = EXCLUDED.period,
    benefits  = EXCLUDED.benefits,
    chat_link = EXCLUDED.chat_link
RETURNING id, developer_id, name, price, period, benefits, chat_link, active, created_at
`

type UpsertSubscriptionPlanParams struct {
	ID          string   `json:"id"`
	DeveloperID string   `json:"developer_id"`
	Name        string   `json:"name"`
	Price       int32    `json:"price"`
	Period      string   `json:"period"`
	Benefits    []string `json:"benefits"`
	ChatLink    string   `json:"chat_link"`
}

func (q *Queries) UpsertSubscriptionPlan(ctx context.Context, arg UpsertSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, upsertSubscriptionPlan,
		arg.ID,
		arg.DeveloperID,
		arg.Name,
		arg.Price,
		arg.Period,
		arg.Benefits,
		arg.ChatLink,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Price,
		&i.Period,
		&i.Benefits,
		&i.ChatLink,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
