import type { Game, GameTheme, User } from './types';

// A pre-seeded developer so the catalog isn't empty on first load.
export const SEED_DEV: User & { passwordHash: string } = {
  id: 'usr_forge',
  username: 'pixelsmith',
  email: 'dev@indieforge.gg',
  role: 'admin',
  isDeveloper: true,
  createdAt: '2025-01-04T10:00:00.000Z',
  passwordHash: 'demo', // mock only
};

type Seed = Omit<
  Game,
  'stats' | 'owned' | 'subscribed' | 'canPlayFree' | 'developerId' | 'developerName'
>;

const theme = (
  accent: string,
  accent2: string,
  background: string,
  layout: GameTheme['layout'] = 'immersive',
): GameTheme => ({ accent, accent2, background, layout, cardShape: 'rounded' });

const base = {
  developerScreenshots: [] as string[],
};

const now = Date.now();
const iso = (daysFromNow: number) => new Date(now + daysFromNow * 86400000).toISOString();

export const SEED_GAMES: Seed[] = [
  {
    id: 'game_emberfall',
    slug: 'emberfall',
    title: 'Emberfall',
    tagline: 'A hand-forged roguelike where every run reshapes the underworld.',
    description:
      "Descend the Emberfall caverns, forge relics from the bones of what you kill, and never take the same path twice. Procedurally smithed dungeons, 40+ relics, and a co-op mode that lets a friend drop into your run from the browser.\n\nDie, learn, reforge. The anvil remembers.",
    genre: 'Roguelike',
    tags: ['pixel-art', 'procedural', 'co-op', 'difficult'],
    coverImage: null,
    screenshots: base.developerScreenshots,
    hasBrowserBuild: true,
    browserBuildUrl: null,
    hasDownloadBuild: true,
    downloadFileName: 'emberfall-win64.zip',
    downloadSizeMB: 184,
    downloadPlatforms: ['Windows', 'Linux'],
    supportsMultiplayer: true,
    pricingModel: 'paid',
    price: 499,
    friendPackDiscount: 30,
    subscription: {
      enabled: true,
      price: 199,
      period: 'month',
      benefits: ['Weekly relic drops', 'Members-only dungeon seeds', 'Name in the credits', 'Discord forge-room'],
    },
    demoDay: { enabled: true, startsAt: iso(-1), endsAt: iso(2), active: true },
    theme: theme('#ff6a2c', '#ffb23e', '#140d0a'),
    status: 'published',
    createdAt: iso(-12),
  },
  {
    id: 'game_neondrift',
    slug: 'neon-drift',
    title: 'Neon Drift',
    tagline: 'Synthwave street racing you can play instantly in the browser.',
    description:
      'Drift through a rain-slicked neon city against eight other players in real-time browser multiplayer. No install, no waiting — click play and you are on the grid.',
    genre: 'Racing',
    tags: ['multiplayer', 'retro', 'sci-fi'],
    coverImage: null,
    screenshots: [],
    hasBrowserBuild: true,
    browserBuildUrl: null,
    hasDownloadBuild: false,
    downloadFileName: null,
    downloadSizeMB: null,
    downloadPlatforms: [],
    supportsMultiplayer: true,
    pricingModel: 'free',
    price: 0,
    friendPackDiscount: 0,
    subscription: { enabled: false, price: 0, period: 'month', benefits: [] },
    demoDay: { enabled: false, startsAt: null, endsAt: null, active: false },
    theme: theme('#38bdf8', '#818cf8', '#0a0f17'),
    status: 'published',
    createdAt: iso(-5),
  },
  {
    id: 'game_hollowroot',
    slug: 'hollowroot',
    title: 'Hollowroot',
    tagline: 'A cozy-creepy metroidvania about a gardener in a dying world.',
    description:
      'Tend forgotten gardens, grow your way through locked doors, and uncover why the roots stopped singing. Atmospheric, story-rich, and quietly unsettling.',
    genre: 'Adventure',
    tags: ['metroidvania', 'atmospheric', 'story-rich', 'pixel-art'],
    coverImage: null,
    screenshots: [],
    hasBrowserBuild: false,
    browserBuildUrl: null,
    hasDownloadBuild: true,
    downloadFileName: 'hollowroot-setup.exe',
    downloadSizeMB: 320,
    downloadPlatforms: ['Windows', 'macOS'],
    supportsMultiplayer: false,
    pricingModel: 'paid',
    price: 349,
    friendPackDiscount: 25,
    subscription: { enabled: false, price: 0, period: 'month', benefits: [] },
    demoDay: { enabled: false, startsAt: null, endsAt: null, active: false },
    theme: theme('#84cc16', '#22d3ee', '#0a1410'),
    status: 'published',
    createdAt: iso(-20),
  },
  {
    id: 'game_anvilborn',
    slug: 'anvilborn',
    title: 'Anvilborn',
    tagline: 'Build a blacksmith empire, one perfect strike at a time.',
    description:
      'A relaxing crafting sim about heating, hammering, and quenching the finest blades in the realm. Subscribe to the smithy for a steady stream of new patterns from the author.',
    genre: 'Simulation',
    tags: ['cozy', 'singleplayer', 'minimalist'],
    coverImage: null,
    screenshots: [],
    hasBrowserBuild: true,
    browserBuildUrl: null,
    hasDownloadBuild: true,
    downloadFileName: 'anvilborn.zip',
    downloadSizeMB: 96,
    downloadPlatforms: ['Windows', 'macOS', 'Linux'],
    supportsMultiplayer: false,
    pricingModel: 'paid',
    price: 0,
    friendPackDiscount: 0,
    subscription: {
      enabled: true,
      price: 149,
      period: 'month',
      benefits: ['New blade patterns weekly', 'Early access builds', 'Vote on the roadmap'],
    },
    demoDay: { enabled: false, startsAt: null, endsAt: null, active: false },
    theme: theme('#f59e0b', '#ef4444', '#140d0a', 'classic'),
    status: 'published',
    createdAt: iso(-2),
  },
  {
    id: 'game_voidloop',
    slug: 'voidloop',
    title: 'Voidloop',
    tagline: 'A one-button bullet-hell about looping time to survive.',
    description:
      'Every death rewinds three seconds. Stack your past selves into a swarm and tear through the void. Fast, brutal, free.',
    genre: 'Shooter',
    tags: ['difficult', 'minimalist', 'retro'],
    coverImage: null,
    screenshots: [],
    hasBrowserBuild: true,
    browserBuildUrl: null,
    hasDownloadBuild: false,
    downloadFileName: null,
    downloadSizeMB: null,
    downloadPlatforms: [],
    supportsMultiplayer: false,
    pricingModel: 'free',
    price: 0,
    friendPackDiscount: 0,
    subscription: { enabled: false, price: 0, period: 'month', benefits: [] },
    demoDay: { enabled: false, startsAt: null, endsAt: null, active: false },
    theme: theme('#a78bfa', '#d946ef', '#0f0a16'),
    status: 'published',
    createdAt: iso(-8),
  },
  {
    id: 'game_lasthearth',
    slug: 'last-hearth',
    title: 'Last Hearth',
    tagline: 'Co-op survival around a fire that must never go out.',
    description:
      'Gather, build, and defend the last warm place in a frozen world. Bring a friend with the Friend Pack and keep the hearth burning together.',
    genre: 'Strategy',
    tags: ['co-op', 'multiplayer', 'atmospheric'],
    coverImage: null,
    screenshots: [],
    hasBrowserBuild: false,
    browserBuildUrl: null,
    hasDownloadBuild: true,
    downloadFileName: 'last-hearth-win.zip',
    downloadSizeMB: 540,
    downloadPlatforms: ['Windows'],
    supportsMultiplayer: true,
    pricingModel: 'paid',
    price: 649,
    friendPackDiscount: 40,
    subscription: { enabled: false, price: 0, period: 'month', benefits: [] },
    demoDay: { enabled: true, startsAt: iso(-1), endsAt: iso(3), active: true },
    theme: theme('#38bdf8', '#f43f5e', '#0a0f17', 'classic'),
    status: 'published',
    createdAt: iso(-30),
  },
];
